### ISSUE TITLE
ノンと申します。先日のもくもく会ありがとうございました

### ISSUE THREAD

**Issue by nonna2525** [inomaru/profile#1]
11月20日のもくもく会に参加しました、ノンと申します。
お話の中でたくさん刺激をもらいました！

私はGitをあまり使わないので、もしよかったらTwitterフォローさせてください！
私のアカウントは@nonnna_299です。

仲良くしてくれると嬉しいです(*^^*)

**Comment by inomaru** [comment]
wow!
今気づきました^^
ありがとうございます！

こちらこそ、よろしくお願いします^^
フォローさせていただきますね！
